### ISSUE TITLE
Error running Easy Coding Standard in latest php7.4-alpine

### ISSUE THREAD

**Issue by j13k** [jakzal/phpqa#290] opened 2021-03-18 02:41 UTC
## Steps to reproduce

Pull the latest image (see digest hash below):

```
php7.4-alpine: Pulling from jakzal/phpqa
Digest: sha256:0cdb0e85988c5b965195bb0345edf27df622e1798779196929921e82cfbe1bce
Status: Image is up to date for jakzal/phpqa:php7.4-alpine
```

Invoke `ecs` tool in a container using the latest image:

```
docker run --init -it --rm -v "$(pwd):/project" -v "$(pwd)/tmp-phpqa:/tmp" -w /project jakzal/phpqa:php7.4-alpine ecs
```

## Stack trace

```
Fatal error: Uncaught Error: Class '_PhpScoper8a7636b3fdaf\Composer\InstalledVersions' not found in /tools/.composer/vendor-bin/tools/vendor/symplify/easy-coding-standard-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php:17
Stack trace:
#0 /tools/.composer/vendor-bin/tools/vendor/symplify/easy-coding-standard-prefixed/vendor/symplify/package-builder/src/Composer/PackageVersionProvider.php(34): _PhpScoper8a7636b3fdaf\Jean85\PrettyVersions::getVersion('symplify/easy-c...')
#1 /tools/.composer/vendor-bin/tools/vendor/symplify/easy-coding-standard-prefixed/vendor/symplify/package-builder/src/Composer/PackageVersionProvider.php(19): Symplify\PackageBuilder\Composer\PackageVersionProvider->getVersion('symplify/easy-c...', 'symplify/sympli...')
#2 /tools/.composer/vendor-bin/tools/vendor/symplify/easy-coding-standard-prefixed/src/Console/EasyCodingStandardConsoleApplication.php(33): Symplify\PackageBuilder\Composer\PackageVersionProvider->provide('symplify/easy-c...')
#3 /tmp/easy_coding_standard_kernel/Conta in /tools/.composer/vendor-bin/tools/vendor/symplify/easy-coding-standard-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php on line 17
```

**Comment by jakzal** [comment] 2021-03-18 11:48
Thanks for reporting. This is caused by https://github.com/symplify/symplify/issues/3056 and should be fixed as soon as ecs phar is updated.

**Comment by jakzal** [comment] 2021-03-19 19:26
Problem's fixed now.

**Closed by jakzal** 2021-03-19 19:26 UTC
