### ISSUE TITLE
Fix builds

### ISSUE THREAD

**Issue by jakzal** [jakzal/phpqa#336] opened 2021-12-25 21:03 UTC
Once there's a solution to https://github.com/composer/composer/issues/10389

**Comment by hopeseekr** [comment] 2021-12-26 04:06
I can fix it...

Point me to your build problem. I just fixed this for a large range of my own projects.

**Comment by jakzal** [comment] 2021-12-26 12:44
It might be a problem with the way composer-bin-plugin or composer itself creates symlinks. I haven’t looked at it too deep yet. If there’s anything to change on our side it will probably be in the jakzal/toolbox repo (see failing builds there).

the problem with allowed-plugins isn’t critical until next year.

**Comment by Seldaek** [comment] 2021-12-28 16:02
> For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins

This is simply a warning and it should not break any builds. We explicitly built this in with a grace period of six months so that we do not disrupt anything and give people time to update their composer.json files. That said yes please do fix it before it becomes a problem. It only requires you to list the plugins like `"allow-plugins": {"foo/bar": true}`, this shouldn't be a ton of work, and it anyway won't have any effect on the end users of your package as they are the ones that have to allow plugins to execute in their projects, your composer.json config has no impact on theirs.

> It might be a problem with the way composer-bin-plugin or composer itself creates symlinks. I haven’t looked at it too deep yet. If there’s anything to change on our side it will probably be in the jakzal/toolbox repo (see failing builds there).

Yes that's more or less what it is, see https://github.com/composer/composer/pull/10402 for an explanation and a way to fix. I'd be curious to get feedback from people encountering issues. I couldn't find exactly the source of `/tools/php-coupling-detector` for toolbox, so I am not sure what it's looking like, but I assume it's doing something similar.

**Comment by jakzal** [comment] 2021-12-30 18:33
Thanks @Seldaek. It seems we're having issues with links to composer created scripts in combination with composer-bin-plugin.

i.e. 

This works fine:

```
composer global require bamarni/composer-bin-plugin
composer global bin tools require akeneo/php-coupling-detector
~/.composer/vendor-bin/php-coupling-detector/vendor/bin/php-coupling-detector
```

This doesn't:
```
ln -sf ${COMPOSER_HOME:-"~/.composer"}/vendor-bin/php-coupling-detector/vendor/bin/php-coupling-detector /usr/local/bin/php-coupling-detector
/usr/local/bin/php-coupling-detector
```

```
/usr/local/bin/php-coupling-detector: cd: line 3: can't cd to ../akeneo/php-coupling-detector/bin: No such file or directory
/usr/local/bin/php-coupling-detector: line 16: /php-coupling-detector: not found
```

composer 2.2.2

**Comment by jakzal** [comment] 2021-12-30 18:46
Actually, it's unrelated to composer-bin-plugin:

```
/toolbox # composer global require akeneo/php-coupling-detector -q
/toolbox # composer self-update
You are already using the latest available Composer version 2.2.2 (stable channel).
/toolbox # composer global require akeneo/php-coupling-detector -q
/toolbox #
/toolbox #
/toolbox # ln -s ~/.composer/vendor/bin/php-coupling-detector /usr/local/bin/php-coupling-detector
/toolbox # /usr/local/bin/php-coupling-detector
/usr/local/bin/php-coupling-detector: cd: line 3: can't cd to ../akeneo/php-coupling-detector/bin: No such file or directory
/usr/local/bin/php-coupling-detector: line 16: /php-coupling-detector: not found
```

**Comment by Seldaek** [comment] 2021-12-30 20:38
OK I see.

So there is one bug here in that we do not detect https://github.com/akeneo/php-coupling-detector/blob/master/bin/php-coupling-detector as a php file I believe because it has a blank line before `<?php` - I fixed that in https://github.com/composer/composer/commit/d1d5d75c5f57d0ac626930748dcca26dbebb57d3

But the other issue is that the symlinking you are doing is going to break the bin proxies we now create as of Composer 2.2, so if any tool you are using has a binary which is a shell script and not PHP, this will still break.

The issue is the symlink changes the resolution of `cd "${0%[/\\]*}"` that we do in our bin proxy to resolve the full path of the real binary from the package. For example if you have

```
/foo/ #project dir
/foo/vendor/bin/bla  #bin proxy created by composer
/foo/vendor/blu/bla/bin/bla #real binary from blu/bla package
/bar/bla -> /foo/vendor/bin/bla #symlink
```

Then when calling `/foo/vendor/bin/bla`, it will resolve current dir to `/foo/vendor/bin` and know to then find the real binary in `../blu/bla/bin/bla`.

If you however call it via a symlink `/bar/bla`, the resolved dir is that of the symlink's location so you get `/bar` and now the relative path is broken.

I am not sure if that one is a solvable problem on our end or not, will need to investigate further.

**Comment by Seldaek** [comment] 2021-12-30 20:56
> I am not sure if that one is a solvable problem on our end or not, will need to investigate further.

Should be fixed by https://github.com/composer/composer/commit/390260c6a689912dbf4c9d41fe36418c44b1d89a actually.. so hopefully now with latest snapshot (`composer self-update --snapshot`) everything should be fine again here.

**Comment by jakzal** [comment] 2021-12-30 22:15
Thanks @Seldaek 🍺  you're a ⭐  Problem solved!

**Comment by jakzal** [comment] 2021-12-30 22:18
I'll update jakzal/toolbox as soon as a new composer version is released.

As for allow-plugins: https://github.com/jakzal/toolbox/issues/415

**Comment by Seldaek** [comment] 2021-12-31 11:23
2.2.3 is [out now](https://github.com/composer/composer/releases/tag/2.2.3)

**Closed** 2021-12-31 15:24 UTC
