### ISSUE TITLE
Problem with running analyze

### ISSUE THREAD

**Issue by sparrowek** [jakzal/phpqa#207] opened 2020-02-23 13:29 UTC
When running analyze like this:

> analyze analyze src/ 

I get error:
```
fatal: There is no path src/vendor/composer/autoload_real.php in the commit
Exception: Command "git 'log' '--format=format:qacommit: %H' '--no-patch' '-L' '5,52:/home/src/vendor/composer/autoload_real.php'" exited with non zero exit code 128:  in /tools/QualityAnalyzer/src/php/Qafoo/Analyzer/Shell.php:54
Stack trace:
#0 /tools/QualityAnalyzer/src/php/Qafoo/Analyzer/Handler/GitDetailed.php(104): Qafoo\Analyzer\Shell->exec('git', Array, Array, '/home/src')
```
The problem is not with my code but the analyze library, because when I have installed it like this:
```
git clone https://github.com/Qafoo/QualityAnalyzer.git
cd QualityAnalyzer
composer install
```
it works successfully.

**Comment by jakzal** [comment] 2020-02-25 11:00
Can you provide more details on how you execute the command? I just tried on a random project and it worked fine. Seems like an issue with the project you're trying to analyse.

**Comment by jakzal** [comment] 2020-04-22 09:35
Closing due to lack of reproducer.

**Closed by jakzal** 2020-04-22 09:35 UTC
